app_booking:
    resource: "@AppBookingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#BladeTesterCalendarBundle:
#    resource: "@BladeTesterCalendarBundle/Resources/config/routing.yml"
#    prefix:   /