conge_index:
    path:     /
    defaults: { _controller: "AppBookingBundle:Conge:index" }
    methods:  GET

conge_show:
    path:     /{id}/show
    defaults: { _controller: "AppBookingBundle:Conge:show" }
    methods:  GET

conge_new:
    path:     /new
    defaults: { _controller: "AppBookingBundle:Conge:new" }
    methods:  [GET, POST]

conge_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBookingBundle:Conge:edit" }
    methods:  [GET, POST]

conge_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBookingBundle:Conge:delete" }
    methods:  DELETE
