services_index:
    path:     /
    defaults: { _controller: "AppBookingBundle:Services:index" }
    methods:  GET

services_show:
    path:     /{id}/show
    defaults: { _controller: "AppBookingBundle:Services:show" }
    methods:  GET

services_new:
    path:     /new
    defaults: { _controller: "AppBookingBundle:Services:new" }
    methods:  [GET, POST]

services_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBookingBundle:Services:edit" }
    methods:  [GET, POST]

services_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBookingBundle:Services:delete" }
    methods:  DELETE
