user_index:
    path:     /
    defaults: { _controller: "AppBookingBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBookingBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "AppBookingBundle:User:new" }
    methods:  [GET, POST]
user_ajaxnew:
    path:     /new
    defaults: { _controller: "AppBookingBundle:User:ajaxnew" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBookingBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBookingBundle:User:delete" }
user_del:
    path:     /supp
    defaults: { _controller: "AppBookingBundle:User:ajaxdel" }

