zone_index:
    path:     /
    defaults: { _controller: "AppBookingBundle:Zone:index" }
    methods:  GET

zone_show:
    path:     /{id}/show
    defaults: { _controller: "AppBookingBundle:Zone:show" }
    methods:  GET

zone_new:
    path:     /new
    defaults: { _controller: "AppBookingBundle:Zone:new" }
    methods:  [GET, POST]

zone_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBookingBundle:Zone:edit" }
    methods:  [GET, POST]

zone_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBookingBundle:Zone:delete" }

