<?php

namespace App\BookingBundle\Repository;

/**
 * HoraireBreaksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireBreaksRepository extends \Doctrine\ORM\EntityRepository
{
}
